var TRANSLATE_PT = { 
	UTIL_SAIBA_MAIS					: 'Saiba mais',
	UTIL_FECHAR						: 'Fechar',

	MENU_EMPRESA					: 'Empresa',
	MENU_PRODUTOS					: 'Produtos',
	MENU_PRODUTOS_FERRAGEM			: 'Ferragem',
	MENU_PRODUTOS_ACESSIBILIDADE	: 'Acessibilidade',
	MENU_PRODUTOS_NAUTICA			: 'Náutica',
	MENU_PRODUTOS_DOBRADIÇA			: 'Dobradiça Industrial',
	MENU_PRODUTOS_MEDIDA			: 'Peças Sob Medida',
	MENU_PRODUTOS_CASE				: 'Case',
	MENU_PRODUTOS_CHURRASCO			: 'Churrasco',
	MENU_PRODUTOS_CATALOGO			: 'Catálogo Virtual',
	MENU_REPRESENTANTES				: 'Representantes',
	MENU_ONDE						: 'Compre Aqui',
	MENU_MIDIA						: 'Mídia',
	MENU_CONTATO					: 'Contato',

	RODAPE_FONE1					: '51 3303.3350',
	RODAPE_FONE2					: '11 2626.9203',
	RODAPE_FONE3					: '19 4040.4722',
	RODAPE_FONE4					: '',

	HOME_BANNER_TITULO				: 'Mahler Inox',
	HOME_BANNER_TEXTO				: 'Bem vindo ao novo website da Mahler, aqui você encontra todas as informações sobre nós e nossos produtos.',
	HOME_TEXTO_VIDEO				: 'Conheça um pouco mais sobre a Mahler, acessando nossos videos.',
	HOME_TEXTO_CATALOGO				: 'Acesse o nosso catálogo virtual e fique por dentro dos produtos oferecidos pela Mahler.',
	HOME_TEXTO_ONDE					: 'Saiba onde encontrar os produtos da Mahler mais pertos de você.',
	HOME_TEXTO_CONTATO				: 'Entre em contato com Mahler através nosso formulário ou ainda envie seu currículo para nós.',

	EMPRESA_TITULO					: 'Quem Somos',
	EMPRESA_TEXTO					: 'No ano de 2015 a Metalúrgica Mahler completa 57 anos de sua fundação. A história começou em 1958 quando os irmãos Nikolai e Alexander Mahler decidiram criar uma empresa, na época chamada de Irmãos Mahler, para produzir dobradiças para assento sanitário com uma durabilidade muito maior que as similares. Elegeram como matéria prima o aço inox, material praticamente desconhecido naquela época. Foi o primeiro de uma série de produtos criados com este material extraordinário, e até hoje esta linha não para de crescer.</p><p>No ano de 1974, com a saída do sócio Alexander, um dos filhos do Sr. Nikolai, o atual diretor-presidente Vitor Hugo Mahler passou a ser sócio da empresa.</p><p>No ano de 2006 a empresa mudou suas instalações para uma nova área com espaço de 16.000 m2, com 4.000 m2 de área construída. A nova fábrica está situada no Distrito Industrial do município de Cachoeirinha, RS, na região metropolitana de Porto Alegre.',

	REPRESENTANTES_TITULO			: this.MENU_REPRESENTANTES,
	REPRESENTANTES_TEXTO			: 'Para consultar a existência de representantes da Indústria Metalúrgica Mahler na sua região selecione um estado na lista ao lado.',
	REPRESENTANTES_NENHUM			: 'Nenhum representante encontrado para o estado selecionado.',

	ONDE_TITULO						: this.MENU_ONDE,
	ONDE_TEXTO						: 'Para consultar a existência de lojas da Indústria Metalúrgica Mahler na sua região selecione um estado na lista ao lado.',
	ONDE_NENHUM						: 'Nenhuma loja encontrada para o estado selecionado.',

	ONDE_LOJISTAS					: 'Lojistas',
	ONDE_CONSUMIDORES				: 'Consumidores',
	ONDE_LOJISTAS_TEXTO				: 'Encontre aqui uma lista completa com nossos representantes comerciais por estado ou região de atuação. Nossos representantes foram selecionados e treinados para atendê-lo com a qualidade e confiança que o líder nacional no segmento de dobradiças e ferragens em aço inox pode oferecer.',
	ONDE_CONSUMIDORES_TEXTO			: 'Encontre aqui uma lista completa de lojas online, ferragens locais, atacados da construção, supermercados e home centers que comercializam os produtos Mahler Inox, para melhor atendê-lo em produtos voltados ao consumidor doméstico.',
	ONDE_SOU_LOJISTA				: 'Sou Lojista',
	ONDE_SOU_CONSUMIDOR				: 'Sou Consumidor',

	ONDE_VENDA_TODOS				: 'Todos tipos de venda',
	ONDE_VENDA_ONLINE				: 'Venda on-line',
	ONDE_VENDA_FONE					: 'Televendas',
	ONDE_VENDA_FISICA				: 'Loja Física',

	MIDIA_VIDEOS 					: 'Vídeos',
	MIDIA_VIDEOS_TEXTO				: 'Aqui você encontra os filmes para TV e Web e conheça um pouco mais sobre nossos produtos, dicas de instalação e história da Mahler Inox',
	MIDIA_ANUNCIOS 					: 'Anúncios',
	MIDIA_ANUNCIOS_TEXTO			: 'Aqui você encontra os criativos veiculados em revistas setoriais, jornais e tabloides',

	CONTATO_FALE					: 'Fale Conosco',
	CONTATO_NOME					: 'Nome',
	CONTATO_FONE					: 'Telefone',
	CONTATO_ASSUNTO					: 'Assunto',
	CONTATO_MENSAGEM				: 'Mensagem',
	CONTATO_ENVIAR					: 'Enviar',
	CONTATO_TRABALHE				: 'Trabalhe Conosco',
	CONTATO_TRABALHE_TEXTO			: 'Este serviço destina-se a candidatos que pleiteiam colocação através de contrato com vínculo empregatício. Envie o seu currículo através de anexo usando como identificação do arquivo o seu nome completo. Seu currículo ficará arquivado por até seis meses.',
	CONTATO_TRABALHE_CV				: 'Clique aqui para enviar o seu curriculum',
	CONTATO_REPRESENTANTE			: 'Seja Representante',
	CONTATO_REPRESENTANTE_TEXTO		: 'A Metalúrgica Mahler está buscando profissionais de vendas para aumentar a sua participação em mercados específicos, com demanda por produtos especiais fabricados em aço inoxidável. Com mais de 55 anos de atuação e conhecimento sobre processos de fabricação em aço inoxidável, a Mahler é reconhecida em toda Brasil e países da AL como referência no segmento.</p><p>Se você se destaca em um dos perfis listados abaixo e quer fazer parte da nossa força de vendas, entre em contato enviando o seu CV.',
	CONTATO_REPRESENTANTE_LOJAS		: 'Lojas de Varejo de ferragem',
	CONTATO_REPRESENTANTE_IND		: 'Industria',
	CONTATO_REPRESENTANTE_CIVIL		: 'Construção civil',
	CONTATO_REPRESENTANTE_HOSP		: 'Hospitalar',
	CONTATO_CURRICULO				: 'Currículo',
	CONTATO_ARQUIVO					: 'Arquivo',
	
	PRODUTO_REFERENCIA				: 'Referência',
	PRODUTO_TAMANHO					: 'Tamanho',
	PRODUTO_ACABAMENTO				: 'Acabamento',
	PRODUTO_ESPECIFICACAO			: 'Especificação',
	PRODUTO_FOTO					: 'Foto',
	PRODUTO_ORCAMENTO				: 'Solicite orçamento',

};

var TRANSLATE_EN = { 
	UTIL_SAIBA_MAIS					: 'Learn more',
	UTIL_FECHAR						: 'Close',

	MENU_EMPRESA					: 'Company',
	MENU_PRODUTOS					: 'Products',
	MENU_PRODUTOS_FERRAGEM			: 'Hardware',
	MENU_PRODUTOS_ACESSIBILIDADE	: 'Accessibility',
	MENU_PRODUTOS_NAUTICA			: 'Nautical',
	MENU_PRODUTOS_DOBRADIÇA			: 'Industrial Hinge',
	MENU_PRODUTOS_MEDIDA			: 'Parts Tailor',
	MENU_PRODUTOS_CASE				: 'Case',
	MENU_PRODUTOS_CHURRASCO			: 'Barbecue',
	MENU_PRODUTOS_CATALOGO			: 'Virtual Catalog',
	MENU_REPRESENTANTES				: 'Representatives',
	MENU_ONDE						: 'Buy Here',
	MENU_MIDIA						: 'Media',
	MENU_CONTATO					: 'Contact',

	RODAPE_FONE1					: '+55 ' + TRANSLATE_PT["RODAPE_FONE1"],
	RODAPE_FONE2					: '+55 ' + TRANSLATE_PT["RODAPE_FONE2"],
	RODAPE_FONE3					: '+55 ' + TRANSLATE_PT["RODAPE_FONE3"],
	RODAPE_FONE4					: '+55 ' + TRANSLATE_PT["RODAPE_FONE4"],

	HOME_BANNER_TITULO				: TRANSLATE_PT["HOME_BANNER_TITULO"],
	HOME_BANNER_TEXTO				: 'Welcome to the new Mahler\'s website, here you can find all information about us and our products.',
	HOME_TEXTO_VIDEO				: 'Learn a little more about Mahler, accessing our videos.',
	HOME_TEXTO_CATALOGO				: 'Visit our online catalog and get inside the products offered by Mahler.',
	HOME_TEXTO_ONDE					: 'Learn where to find products of Mahler nearer you.',
	HOME_TEXTO_CONTATO				: 'Contact Mahler through our form or send your resume to us.',

	EMPRESA_TITULO					: 'About Us',
	EMPRESA_TEXTO					: 'In the year 2015 the Metallurgical complete Mahler 57 years of its foundation. The story began in 1958 when the brothers Nikolai and Alexander Mahler decided to create a company, then called Mahler Brothers to produce hinges for toilet seat with much greater durability than similar. Elected as raw material stainless steel, virtually unknown material at the time. It was the first of a series of products created with this extraordinary material, and even today this line is constantly increasing.</p><p>In 1974, with the departure of Alexander partner, a son of Mr. Nikolai, the current CEO Victor Hugo Mahler became partner of the company.</p><p>In 2006 the company moved its facilities to a new area with space of 16,000 m2, with 4,000 m2 of built area. The new plant is located in the industrial district of the city of Cachoeirinha, RS, in the metropolitan region of Porto Alegre.',

	REPRESENTANTES_TITULO			: this.MENU_REPRESENTANTES,
	REPRESENTANTES_TEXTO			: 'Para consultar a existência de representantes da Indústria Metalúrgica Mahler na sua região selecione um estado na lista ao lado.',
	REPRESENTANTES_NENHUM			: 'Nenhum representante encontrado para o estado selecionado.',

	ONDE_TITULO						: this.MENU_ONDE,
	ONDE_TEXTO						: 'Para consultar a existência de lojas da Indústria Metalúrgica Mahler na sua região selecione um estado na lista ao lado.',
	ONDE_NENHUM						: 'Nenhuma loja encontrada para o estado selecionado.',

	ONDE_LOJISTAS					: 'Storekeepers',
	ONDE_CONSUMIDORES				: 'Consumers',
	ONDE_LOJISTAS_TEXTO				: 'Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry\'s standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book. It has survived not only five centuries, but also the leap into electronic typesetting, remaining essentially unchanged. It was popularised in the 1960s with the release of Letraset sheets containing Lorem Ipsum passages, and more recently with desktop publishing software like Aldus PageMaker including versions of Lorem Ipsum.',
	ONDE_CONSUMIDORES_TEXTO			: 'Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry\'s standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book. It has survived not only five centuries, but also the leap into electronic typesetting, remaining essentially unchanged. It was popularised in the 1960s with the release of Letraset sheets containing Lorem Ipsum passages, and more recently with desktop publishing software like Aldus PageMaker including versions of Lorem Ipsum.',	
	ONDE_SOU_LOJISTA				: 'I am Storekeeper',
	ONDE_SOU_CONSUMIDOR				: 'I\'m Consumer',

	ONDE_VENDA_TODOS				: 'All for Sale',
	ONDE_VENDA_ONLINE				: 'Online Sales',
	ONDE_VENDA_FONE					: 'Tele Sales',
	ONDE_VENDA_FISICA				: 'Store Sales',

	MIDIA_VIDEOS 					: 'Videos',
	MIDIA_VIDEOS_TEXTO				: 'Here the films for TV and web and learn a little more about our products, installation tips and history of Mahler Inox',
	MIDIA_ANUNCIOS 					: 'Advertisements',
	MIDIA_ANUNCIOS_TEXTO			: 'Here the creative served in trade journals, newspapers and tabloids',

	CONTATO_FALE					: 'Contact Us',
	CONTATO_NOME					: 'Name',
	CONTATO_FONE					: 'Phone',
	CONTATO_ASSUNTO					: 'Subject',
	CONTATO_MENSAGEM				: 'Message',
	CONTATO_ENVIAR					: 'Send',
	CONTATO_TRABALHE				: 'Work with us',
	CONTATO_TRABALHE_TEXTO			: 'This service is intended for applicants for placement under contract with employment. Submit your resume through attachment using file ID as your full name. Your resume will be filed for up to six months.',
	CONTATO_TRABALHE_CV				: 'Click here to send your resume',
	CONTATO_REPRESENTANTE			: 'Be a Representative',
	CONTATO_REPRESENTANTE_TEXTO		: 'The Metallurgical Mahler is seeking sales professionals to increase their participation in specific markets, with demand for special products made of stainless steel. With over 55 years of experience and knowledge of manufacturing processes in stainless steel, the Mahler is recognized throughout Brazil and Latin American countries as a reference in the segment.</p><p>If you stand in one of the profiles listed below and want to join our sales force, contact by sending your resume.',
	CONTATO_REPRESENTANTE_LOJAS		: 'Hardware Retail Stores',
	CONTATO_REPRESENTANTE_IND		: 'Industry',
	CONTATO_REPRESENTANTE_CIVIL		: 'Building',
	CONTATO_REPRESENTANTE_HOSP		: 'Hospital',
	CONTATO_CURRICULO				: 'Resume',
	CONTATO_ARQUIVO					: 'File',

	PRODUTO_REFERENCIA				: 'Reference',
	PRODUTO_TAMANHO					: 'Size',
	PRODUTO_ACABAMENTO				: 'Finish',
	PRODUTO_ESPECIFICACAO			: 'Specification',
	PRODUTO_FOTO					: 'Picture',
	PRODUTO_ORCAMENTO				: 'Request budget',

};

var TRANSLATE_ES = { 
	UTIL_SAIBA_MAIS					: 'Leer más',
	UTIL_FECHAR						: 'Cerrar',

	MENU_EMPRESA					: TRANSLATE_PT["MENU_EMPRESA"],
	MENU_PRODUTOS					: 'Productos',
	MENU_PRODUTOS_FERRAGEM			: 'Hardware',
	MENU_PRODUTOS_ACESSIBILIDADE	: 'Accesibilidad',
	MENU_PRODUTOS_NAUTICA			: 'Nautico',
	MENU_PRODUTOS_DOBRADIÇA			: 'Bisagra Industrial',
	MENU_PRODUTOS_MEDIDA			: 'Piezas a medida',
	MENU_PRODUTOS_CASE				: 'Caso',
	MENU_PRODUTOS_CHURRASCO			: 'Barbacoa',
	MENU_PRODUTOS_CATALOGO			: TRANSLATE_PT["MENU_PRODUTOS_CATALOGO"],
	MENU_REPRESENTANTES				: TRANSLATE_PT["MENU_REPRESENTANTES"],
	MENU_ONDE						: 'Comprar Aquí',
	MENU_MIDIA						: 'Medios',
	MENU_CONTATO					: 'Contacto',

	RODAPE_FONE1					: TRANSLATE_EN["RODAPE_FONE1"],
	RODAPE_FONE2					: TRANSLATE_EN["RODAPE_FONE2"],
	RODAPE_FONE3					: TRANSLATE_EN["RODAPE_FONE3"],
	RODAPE_FONE4					: TRANSLATE_EN["RODAPE_FONE4"],

	HOME_BANNER_TITULO				: TRANSLATE_PT["HOME_BANNER_TITULO"],
	HOME_BANNER_TEXTO				: 'Bienvenido a la nueva página web de la Mahler, aquí se puede encontrar toda la información sobre nosotros y nuestros productos.',
	HOME_TEXTO_VIDEO				: 'Aprenda un poco más acerca de Mahler, acceder a nuestros vídeos.',
	HOME_TEXTO_CATALOGO				: 'Visite nuestro catálogo en línea y obtener el interior de los productos ofrecidos por Mahler.',
	HOME_TEXTO_ONDE					: 'Aprenda dónde encontrar productos de Mahler más cerca usted.',
	HOME_TEXTO_CONTATO				: 'Póngase en contacto con Mahler a través de nuestro formulario o enviar su hoja de vida para nosotros.',

	EMPRESA_TITULO					: 'Sobre Nosotros',
	EMPRESA_TEXTO					: 'En el año 2015 las Metalúrgica Mahler completa 57 años de su fundación. La historia comenzó en 1958 cuando los hermanos Nikolai y Alexander Mahler decidieron crear una empresa, entonces llamada Mahler Hermanos para producir bisagras para asiento de inodoro con mucha mayor durabilidad que similar. Elegido como el acero inoxidable de la materia prima, material de prácticamente desconocido en el momento. Fue la primera de una serie de productos creados con este material extraordinario, y aún hoy en día esta línea está en constante aumento.</p><p>En 1974, con la salida del socio Alexander, un hijo del Sr. Nikolai, el actual CEO Victor Hugo Mahler se convirtió en socio de la empresa.</p><p>En 2006 la empresa se trasladó sus instalaciones a una nueva área con espacio de 16.000 m2, con 4.000 m2 de superficie construida. La nueva planta está ubicada en el distrito industrial de la ciudad de Cachoeirinha, RS, en la región metropolitana de Porto Alegre.',

	REPRESENTANTES_TITULO			: this.MENU_REPRESENTANTES,
	REPRESENTANTES_TEXTO			: 'Para consultar a existência de representantes da Indústria Metalúrgica Mahler na sua região selecione um estado na lista ao lado.',
	REPRESENTANTES_NENHUM			: 'Nenhum representante encontrado para o estado selecionado.',

	ONDE_TITULO						: this.MENU_ONDE,
	ONDE_TEXTO						: 'Para consultar a existência de lojas da Indústria Metalúrgica Mahler na sua região selecione um estado na lista ao lado.',
	ONDE_NENHUM						: 'Nenhuma loja encontrada para o estado selecionado.',

	ONDE_LOJISTAS					: 'Tenderos',
	ONDE_CONSUMIDORES				: 'Consumidores',
	ONDE_LOJISTAS_TEXTO				: 'Aquí hay una lista completa de nuestros representantes de ventas por estado o región de operación. Se seleccionaron Nuestros representantes y capacitados para servirle con la calidad y fiabilidad que el líder nacional en las bisagras de acero inoxidable y el segmento de hardware puede ofrecer.',
	ONDE_CONSUMIDORES_TEXTO			: 'Aquí está la lista completa de tiendas en línea, sitios de accesorios, atacaron el edificio, supermercados y centros para el hogar que comercializan productos Mahler Inox para servirle mejor en productos dirigidos al consumidor doméstico.',	
	ONDE_SOU_LOJISTA				: 'Soy Tendero',
	ONDE_SOU_CONSUMIDOR				: 'Soy Consumidor',

	ONDE_VENDA_TODOS				: 'Todo para la venta',
	ONDE_VENDA_ONLINE				: 'Sale Online',
	ONDE_VENDA_FONE					: 'Televentas',
	ONDE_VENDA_FISICA				: 'Tienda Ubicación',

	MIDIA_VIDEOS 					: 'Videos',
	MIDIA_VIDEOS_TEXTO				: 'Aquí las películas para televisión y web y aprender un poco más sobre nuestros productos, consejos para la instalación y la historia de Mahler Inox',
	MIDIA_ANUNCIOS 					: 'Anuncios',
	MIDIA_ANUNCIOS_TEXTO			: 'Aquí la creatividad sirve en revistas especializadas, periódicos y tabloides',

	CONTATO_FALE					: 'Contáctenos',
	CONTATO_NOME					: 'Nombre',
	CONTATO_FONE					: 'Teléfono',
	CONTATO_ASSUNTO					: 'Sujeto',
	CONTATO_MENSAGEM				: 'Mesaje',
	CONTATO_ENVIAR					: TRANSLATE_PT["CONTATO_ENVIAR"],
	CONTATO_TRABALHE				: 'Trabaja con Nosotros',
	CONTATO_TRABALHE_TEXTO			: 'Este servicio está dirigido a los solicitantes de la colocación bajo contrato con el empleo. Envía tu CV a través del apego usando el archivo ID como su nombre completo. Su currículum será presentada durante un máximo de seis meses.',
	CONTATO_TRABALHE_CV				: 'Haga clic aquí para enviar su currículum.',
	CONTATO_REPRESENTANTE			: 'Sé Representante',
	CONTATO_REPRESENTANTE_TEXTO		: 'La Metalúrgica Mahler está buscando profesionales de ventas para aumentar su participación en mercados específicos, con la demanda de productos especiales de acero inoxidable. Con más de 55 años de experiencia y conocimiento de los procesos de fabricación en acero inoxidable, la Mahler es reconocido en todo Brasil y los países de América Latina como una referencia en el segmento.</p><p>Si usted está parado en uno de los perfiles que figuran a continuación y desea unirse a nuestra fuerza de ventas, contacto mediante el envío de su currículum.',
	CONTATO_REPRESENTANTE_LOJAS		: 'Hardware Retail Stores',
	CONTATO_REPRESENTANTE_IND		: 'Industria',
	CONTATO_REPRESENTANTE_CIVIL		: 'Edificio',
	CONTATO_REPRESENTANTE_HOSP		: 'Hospital',
	CONTATO_CURRICULO				: 'Currículum',
	CONTATO_ARQUIVO					: 'Archivo',

	PRODUTO_REFERENCIA				: 'Referencia',
	PRODUTO_TAMANHO					: 'Tamaño',
	PRODUTO_ACABAMENTO				: 'Acabado',
	PRODUTO_ESPECIFICACAO			: 'Especificación',
	PRODUTO_FOTO					: 'Foto',
	PRODUTO_ORCAMENTO				: 'Solicitud de presupuesto',

};
